apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-locations-producer
  name: udaconnect-locations-producer
spec:
  ports:
  - name: "5003"
    port: 5003
    targetPort: 5003
    nodePort: 30003
  selector:
    service: udaconnect-locations-producer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-locations-producer
  name: udaconnect-locations-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-locations-producer
  template:
    metadata:
      labels:
        service: udaconnect-locations-producer
    spec:
      containers:
      - image: kkinger/udaconnect-locations-producer:latest
        name: udaconnect-locations-producer
        imagePullPolicy: Always
        env:
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: TOPIC_NAME
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_SERVER
      restartPolicy: Always
