apiVersion: v1
kind: Service
metadata:
  labels:
    service: udaconnect-locations-consumer
  name: udaconnect-locations-consumer
spec:
  ports:
  - name: "5002"
    port: 5002
    targetPort: 5002
    nodePort: 30002
  selector:
    service: udaconnect-locations-consumer
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: udaconnect-locations-consumer
  name: udaconnect-locations-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      service: udaconnect-locations-consumer
  template:
    metadata:
      labels:
        service: udaconnect-locations-consumer
    spec:
      containers:
      - image: kkinger/udaconnect-locations-consumer:latest
        name: udaconnect-locations-consumer
        imagePullPolicy: Always
        env:
        - name: TOPIC_NAME
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: TOPIC_NAME
        - name: KAFKA_SERVER
          valueFrom:
            configMapKeyRef:
              name: kafka-env
              key: KAFKA_SERVER
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always
